version: "3.3"

# uffizzi integration
x-uffizzi:
  ingress:
    service: portal
    port: 8080

services:

  registry:
    image: "${REGISTRY_IMAGE}"
    container_name: registry
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID

  core:
    image: "${CORE_IMAGE}"
    container_name: harbor-core
    env_file:
      - ./common/config/core/env
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID

  portal:
    image: "${PORTAL_IMAGE}"
    container_name: harbor-portal
    restart: always
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - NET_BIND_SERVICE

  # jobservice:
  #   image: "${JOBSERVICE_IMAGE}"
  #   container_name: harbor-jobservice
  #   env_file:
  #     - ./common/config/jobservice/env
  #   restart: always
  #   cap_drop:
  #     - ALL
  #   cap_add:
  #     - CHOWN
  #     - SETGID
  #     - SETUID

  notary-server:
    image: "${SERVER_IMAGE}"
    environment:
      DB_URL: postgres://postgres:postgres@localhost:5432

  notary-signer:
    image: "${SIGNER_IMAGE}"
    environment:
      DB_URL: postgres://postgres:postgres@localhost:5432
    container_name: notary-signer
    restart: always
    networks:
      harbor-notary:
      notary-sig:
        aliases:
          - notarysigner

  # signer:
  #   image: "${SIGNER_IMAGE}"
  #   networks:
  #     mdb:
  #     sig:
  #       aliases:
  #         - notarysigner
  #   # entrypoint: /usr/bin/env sh
  #   # command: -c "./migrations/migrate.sh && notary-signer -config=fixtures/signer-config.postgres.json"
  #   environment:
  #     # MIGRATIONS_PATH: migrations/signer/postgresql
  #     DB_URL: postgres://postgres:postgres@localhost:5432
  #   depends_on:
  #     - postgresql

  postgresql:
    image: postgres:latest
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=password
    networks:
      - mdb
    volumes:
      # - ./notarysql/postgresql-initdb.d:/docker-entrypoint-initdb.d
      - notary_data:/var/lib/postgresql
    ports:
      - 5432:5432
    command: -l
volumes:
  notary_data:
    external: false

networks:
  mdb:
    external: false
  sig:
    external: false
